title: "simplezinho"
author: "Giovana Morais"
github_repo: "giovana-morais/simplezinho"
email: giovana.vmorais@gmail.com

permalink: /:slug.html
theme_config:
  date_format: "%d-%m-%Y"

navigation:
 - name: About
   link: /about
 - name: Projects
   link: /projects
 - name: CV
   link: /resume
 # - name: Research
 #   link: /research
 - name: Publications
   link: /publications
 - name: Blog
   link: /blog
